- alias: Sun fading
  id: Sun_fading
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    below: 10.5
  action:
  - service: scene.turn_on
    entity_id: scene.sun_fading
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sun_going_down
- alias: Turn more lights on as the sun gets dimmer
  id: more_lights_sun_dimmer
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.sun_inhibit_action
      state: 'off'
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.more_lights
- id: more_lights_sun_dimmer_nodining
  alias: Turn more lights on as the sun gets dimmer Nodining
  trigger:
  - below: '3.5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.sun_inhibit_action
      state: 'off'
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
  action:
  - data:
      entity_id: scene.more_lights_nodining
    service: scene.turn_on
- alias: Dusk all lights on Nodining
  id: dusk_all_lights_on_nodining
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.sun_inhibit_action
      state: 'off'
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_on_nodining
- alias: Dusk all lights on
  id: dusk_all_lights_on
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.sun_inhibit_action
      state: 'off'
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_on
- alias: Goodnight normal
  id: goodnight
  trigger:
    platform: time
    at: '22:20:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sun
    - condition: state
      entity_id: input_boolean.latenight
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_off
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sun_going_down
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sun_inhibit_action
- alias: game time
  id: game_time
  trigger:
    platform: time
    at: '22:20:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - sat
    - condition: state
      entity_id: input_boolean.latenight
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.gaming_time
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sun_going_down
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sun_inhibit_action
- alias: chip night
  id: chip_night
  trigger:
    platform: time
    at: '19:00:00'
  condition:
  - condition: time
    weekday:
    - fri
  action:
  - service: scene.turn_on
    entity_id: scene.dinner_time
- id: gaming_goodnight
  alias: gaming_goodnight
  trigger:
  - at: 02:00:00
    platform: time
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - sat
    - condition: state
      entity_id: input_boolean.latenight
      state: 'off'
  action:
  - data:
      entity: light.front_room_table_lamp
    service: light.turn_off
- alias: Fish Air pump on morning
  id: fish_air_on
  trigger:
    platform: time
    at: 06:00:00
  action:
  - service: switch.turn_on
    entity_id: switch.Fish_air_pump
- alias: Fish Air pump off evening
  id: fish_air_off
  trigger:
    platform: time
    at: '18:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.Fish_air_pump
- alias: Reset Automations
  id: reset_automation
  trigger:
    platform: time
    at: 00:00:01
  action:
  - service: automation.turn_on
    entity_id: automation.Dusk_all_lights_on
  - service: automation.turn_on
    entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer
- alias: Good morning nodining
  id: good_morning_nodining
  trigger:
    platform: time
    at: 05:29:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.good_morning_nodining
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.alarm_sequence_running
- alias: WakeyWakeyRiseAndShineNodining
  id: wake_up_early_nodining
  trigger:
    platform: time
    at: 05:50:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.wakey_wakey_nodining
- alias: Reset bedroom light to sensible levels Nodining
  id: bed_light_sensible_nodining
  trigger:
    platform: time
    at: 06:20:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on_nodining
- alias: Good morning holidays
  id: good_morning_holidays
  trigger:
    platform: time
    at: 07:00:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.good_morning
- alias: Good morning
  id: good_morning
  trigger:
    platform: time
    at: 05:29:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.good_morning
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.alarm_sequence_running
- alias: WakeyWakeyRiseAndShine
  id: wake_up_early
  trigger:
    platform: time
    at: 05:50:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.wakey_wakey
- alias: Reset bedroom light to sensible levels
  id: bed_light_sensible
  trigger:
    platform: time
    at: 06:20:00
  condition:
    condition: and
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 0:30:00
    - condition: state
      entity_id: input_boolean.dining_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.holiday
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on
- alias: Turn off lights after sunrise
  id: lights_off_after_sunrise
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    above: 10.5
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_off
  - service: automation.turn_on
    entity_id: automation.Dusk_all_lights_on
  - service: automation.turn_on
    entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.alarm_sequence_running
- alias: Bedroom tap face button no sunset
  id: tap2_lights_off_no_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: pressed
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_off_manual
- alias: Bedroom tap face button after sunset
  id: tap2_lights_off_after_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: pressed
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.all_lights_off_manual
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sun_inhibit_action
- alias: Bedroom tap button 2 bathroom run
  id: tap2_bathroom_run
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Two
    payload: pressed
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_landing_light
- alias: Bedroom tap button 3 kitchen run
  id: tap2_kitchen_run
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Three
    payload: pressed
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_to_kitchen
- id: tort_tap_all_toggle
  alias: Tortoise tap all toggle
  trigger:
  - payload: pressed
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Face
  condition: []
  action:
  - service: switch.toggle
    data:
      entity_id:
      - switch.dining_room_sunshine
      - switch.kitchen_sunshine
- id: tort_tap_dining_toggle
  alias: Tortoise tap dining toggle
  trigger:
  - payload: pressed
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Two
  condition: []
  action:
  - service: switch.toggle
    data:
      entity_id: switch.dining_room_sunshine
- id: tort_tap_kitchen_toggle
  alias: Tortoise tap kitchen toggle
  trigger:
  - payload: pressed
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Four
  condition: []
  action:
  - service: switch.toggle
    data:
      entity_id: switch.kitchen_sunshine
- id: kitchen_sensor_lights_on
  alias: Kitchen under cupboard lights
  trigger:
  - entity_id: binary_sensor.kitchen_motion_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kitmocorr
    state: 'off'
  action:
  - data:
      entity_id: light.kitchen_under_cupboard
    entity_id: light.kitchen_under_cupboard
    service: light.toggle
  - data:
      entity_id: input_boolean.kitmocorr
    service: input_boolean.turn_on
- id: kitchen_sensor_lights_off
  alias: Kitchen under cupboard lights no motion
  trigger:
  - entity_id: binary_sensor.kitchen_motion_motion
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.kitmocorr
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.kitmocorr
    service: input_boolean.turn_off
- id: doorbell
  alias: Doorbell
  trigger:
  - entity_id: binary_sensor.doorbell_contact
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.normal_bell
    state: 'on'
  action:
  - data:
      content_type: music
      media_location: http://apollo.lucien.me.uk/~dave/doorbell/sound.mp3
      play_length: 00:00:04
      sonos_entity: media_player.kitchen
      volume: '0.60'
    entity_id: script.audio_alert
    service: script.audio_alert
  - data:
      message: There's somebody at the door
      title: Doorbell pressed
    service: notify.ALL_DEVICES
- id: doorbell_halloween
  alias: Doorbell Halloween
  trigger:
  - entity_id: binary_sensor.doorbell_contact
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.halloween_bell
    state: 'on'
  action:
  - data:
      variables:
        content_type: music
        media_location: http://apollo.lucien.me.uk/~dave/doorbell/toccataandfugue.mp3
        play_length: 00:00:08
        sonos_entity: media_player.kitchen
        volume: '0.60'
    entity_id: script.audio_alert
    service: script.turn_on
- id: doorbell_christmas
  alias: Doorbell Christmas
  trigger:
  - entity_id: binary_sensor.doorbell_contact
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.christmas_bell
    state: 'on'
  action:
  - data:
      variables:
        content_type: music
        media_location: http://apollo.lucien.me.uk/~dave/doorbell/christmas.mp3
        play_length: 00:00:04
        sonos_entity: media_player.kitchen
        volume: '0.60'
    entity_id: script.audio_alert
    service: script.turn_on
- alias: Fridge Door Alarm
  id: fridge_door_alarm
  trigger:
    platform: state
    entity_id: sensor.fridge_door
    from: closed
    to: open
    for:
      hours: 0
      minutes: 0
      seconds: 120
  action:
  - service: notify.ios_daves_iphone
    data:
      title: Fridge Door alert
      message: Fridge door has been open for two minutes
  - service: notify.ios_maries_iphone
    data:
      title: Fridge Door alert
      message: Fridge door has been open for two minutes
- alias: Start HomeKit
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:05
  - service: homekit.start
  id: eefee051dc0a49f1a8773e0e7c200386
- alias: Swap to halloween bell
  id: halloween_bell_swap_to
  trigger:
  - at: 02:10:00
    platform: time
  condition:
    condition: template
    value_template: '{{ ((now().month == 10) and (now().day == 31)) }}'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.halloween_bell
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.normal_bell
- alias: Swap from halloween bell
  id: halloween_bell_swap_from
  trigger:
  - at: 02:10:00
    platform: time
  condition:
    condition: template
    value_template: '{{ ((now().month == 11) and (now().day == 1)) }}'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.halloween_bell
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.normal_bell
- alias: Swap to christmas bell
  id: christmas_bell_swap_to
  trigger:
  - at: 02:10:00
    platform: time
  condition:
    condition: template
    value_template: '{{ ((now().month == 12) and (now().day == 20)) }}'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.christmas_bell
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.normal_bell
- alias: Swap from christmas bell
  id: christmas_bell_swap_from
  trigger:
  - at: 02:10:00
    platform: time
  condition:
    condition: template
    value_template: '{{ ((now().month == 1) and (now().day == 6)) }}'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.normal_bell
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.christmas_bell
- id: '1570360116439'
  alias: Tortoise tap heat toggle
  trigger:
  - payload: pressed
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Three
  condition: []
  action:
  - data:
      entity_id: switch.small_viv_heat
    service: switch.toggle
  - data:
      entity_id: switch.large_viv_heat
    service: switch.toggle
  - data:
      entity_id: light.tortoise_room
    service: light.turn_off
- id: '1570360445400'
  alias: Tortoise heat auto-on
  trigger:
  - at: '18:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.tortheaters
    state: 'on'
  action:
  - data:
      entity_id: switch.small_viv_heat
    service: switch.turn_on
  - data:
      entity_id: switch.large_viv_heat
    service: switch.turn_on
- id: '1570360519100'
  alias: Tortoise heat auto-off
  trigger:
  - at: 06:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.small_viv_heat
    service: switch.turn_off
  - data:
      entity_id: switch.large_viv_heat
    service: switch.turn_off
- id: '1575215443800'
  alias: Christmas Decorations on
  description: Switch Christmas decorations on as sun is going down.
  trigger:
  - below: '5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: state
    entity_id: input_boolean.christmas_decs
    state: 'on'
  action:
  - data:
      entity_id: switch.porch_switch
    service: switch.turn_on
  - data:
      entity_id: switch.living_room_decs
    service: switch.turn_on
- id: '1575216097000'
  alias: Christmas Decorations off
  description: Switch off Christmas decorations when it's getting late
  trigger:
  - at: '22:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.christmas_decs
    state: 'on'
  action:
  - data:
      entity_data: porch_switch
    service: switch.turn_off
  - data:
      entity_data: living_room_decs
    service: switch.turn_off
