homeassistant:
  name: Home
  latitude: 52.260149410781
  longitude: -0.6739781057483401
  elevation: 65
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

recorder:
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret mysql_password
  exclude:
    entities:
      - media_player.living_room_tv
      - sun.sun
    domains:
      - media_player

system_health:

light:
  platform: hue
  host: 192.168.20.133

# Enables the frontend
frontend:

http:
  ssl_certificate: /etc/letsencrypt/live/apollo.lucien.me.uk/fullchain.pem
  ssl_key: /etc/letsencrypt/live/apollo.lucien.me.uk/privkey.pem
  base_url: https://apollo.lucien.me.uk:8123/
  login_attempts_threshold: 10
  ip_ban_enabled: true

# Checks for available updates
updater:

# Discover some devices automatically (necessary for Philips Hue)
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Configuration panel enablement.
config:

# Track the sun
sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: hass
  username: homeassistant
  password: !secret mqtt_ha_password

sensor: !include config/sensors.yaml

zone: !include config/zones.yaml

#device_tracker: !include config/device_tracker.yaml

switch: !include config/switches.yaml

group: !include config/group/lights.yaml

scene: !include config/scenes.yaml

automation: !include automations.yaml

shell_command: !include config/shellcommands.yaml

script: !include config/scripts.yaml

input_text: !include config/inputtext.yaml

#camera:
#  - platform: local_file
#    file_path: /home/dave/.tort-temps/tort-cage-temp-history.png
#    name: torttemps
#    #  - platform: generic
#    #still_image_url: http://90.155.51.236/Streaming/channels/1/picture 
#    #username: admin
#    #password: !secret camera_password
#    #name: tortsnapshot

sonos:
#  media_player:
#    interface_addr: 192.168.30.187
  media_player:
    hosts:
      - 192.168.30.190
      - 192.168.30.156
      - 192.168.30.131

media_player:
  - platform: samsungtv
    host: 90.155.51.229
    port: 8001
    name: living room tv
    mac: CC:B1:1A:C3:37:72

homekit:
   auto_start: false
   filter:
      include_domains:
         - light
         - media_player

ios:
  health_check: true
  push_categories:
    - name: Generic
      identifiier: 'Generic'

input_boolean: !include config/inputbool.yaml
    
