- id: Sun_fading
  alias: 'Sun fading'
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    below: 10.5
  action:
    - service: scene.turn_on
      entity_id: scene.sun_fading
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_going_down

- alias: 'Turn more lights on as the sun gets dimmer'
  id: more_lights_sun_dimmer
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.sun_inhibit_action
        state: 'off'
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.more_lights

- alias: 'Turn more lights on as the sun gets dimmer Nodining'
  id: more_lights_sun_dimmer_nodining
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.sun_inhibit_action
        state: 'off'
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.more_lights_nodining

- alias: 'Dusk all lights on Nodining'
  id: dusk_all_lights_on_nodining
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.sun_inhibit_action
        state: 'off'
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_on_nodining

- alias: 'Dusk all lights on'
  id: dusk_all_lights_on
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.sun_inhibit_action
        state: 'off'
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_on

- alias: 'Goodnight dance night'
  id: dance_goodnight
  trigger:
    platform: time
    at: "22:30:00"
  condition:
    - condition: time
      weekday:
        - mon
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_going_down
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Goodnight normal'
  id: goodnight
  trigger:
    platform: time
    at: "22:20:00"
  condition:
    - condition: time
      weekday:
        - tue
        - wed
        - thu
        - sat
        - sun
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_going_down
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_inhibit_action

- id: game_time
  alias: game time
  trigger:
    platform: time
    at: "22:20:00"
  condition:
    - condition: time
      weekday:
        - fri
  action:
    - service: scene.turn_on
      entity_id: scene.gaming_time
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_going_down
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'gaming_goodnight'
  id: gaming_goodnight
  trigger:
    platform: time
    at: "00:00:00"
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off

- alias: 'Tortoises night night'
  id: torts_night_night
  trigger:
    platform: time
    at: "18:00:00"
  condition:
    condition: state
    entity_id: input_boolean.torts_sun_based
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_off

- alias: 'tortoise sundown'
  id: torts_sundown
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: state
    entity_id: input_boolean.torts_sun_based
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_off

- alias: 'Tortoise heating on'
  id: tort_heating_on
  trigger:
    platform: time
    at: "21:30:00"
  condition:
    condition: state
    entity_id: input_boolean.tortheaters
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.Tortoise_ceramic_heat_on
      
- alias: 'Tortoise sunrise'
  id: tort_sunrise
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    above: 0.0
  condition:
    condition: state
    entity_id: input_boolean.torts_sun_based
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_on
    - service: scene.turn_on
      entity_id: scene.Tortoise_ceramic_heat_off

- alias: 'Tortoises good morning'
  id: tort_good_morning
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    condition: state
    entity_id: input_boolean.torts_sun_based
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_on
    - service: scene.turn_on
      entity_id: scene.Tortoise_ceramic_heat_off

# This next one resets all automations to on at just after midnight, so that automations which
# are turned off as part of a manual override (a button push) reset to on again
- alias: 'Reset Automations'
  id: reset_automation
  trigger:
    platform: time
    at: "00:00:01"
  action:
    - service: automation.turn_on
      entity_id: automation.Dusk_all_lights_on
    - service: automation.turn_on
      entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer

- alias: 'Good morning nodining'
  id: good_morning_nodining
  trigger:
    platform: time
    at: "05:29:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.good_morning_nodining
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.alarm_sequence_running

- alias: 'WakeyWakeyRiseAndShineNodining'
  id: wake_up_early_nodining
  trigger:
    platform: time
    at: "05:50:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wakey_wakey_nodining

- alias: 'Reset bedroom light to sensible levels Nodining'
  id: bed_light_sensible_nodining
  trigger:
    platform: time
    at: "06:20:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on_nodining

- alias: 'Good morning'
  id: good_morning
  trigger:
    platform: time
    at: "05:29:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.good_morning
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.alarm_sequence_running

- alias: 'WakeyWakeyRiseAndShine'
  id: wake_up_early
  trigger:
    platform: time
    at: "05:50:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.wakey_wakey

- alias: 'Reset bedroom light to sensible levels'
  id: bed_light_sensible
  trigger:
    platform: time
    at: "06:20:00"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "0:30:00"
      - condition: state
        entity_id: input_boolean.dining_override
        state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on

# As a backstop, this also turns on the automations which the tap "off" buttons turn off to prevent the lights
# coming back on in summer when we're in bed early.
- alias: 'Turn off lights after sunrise'
  id: lights_off_after_sunrise
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    above: 10.5
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: automation.turn_on
      entity_id: automation.Dusk_all_lights_on
    - service: automation.turn_on
      entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.alarm_sequence_running

#
# Boggo standard pressed button on the tap - the sunset sequence hasn't started.
# result: just turn off lights.
#
- alias: 'Hallway tap face button no sunset'
  id: tap1_lights_off_no_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_room_off

#
# Special case tap off button - sunset sequence has started, ignore remainder of sequence.
# result: turn off lights, and set inhibit input_boolean to stop other automations firing.
#
- alias: 'Hallway tap face button after sunset'
  id: tap1_lights_off_after_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_room_off
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Bedroom tap face button no sunset'
  id: tap2_lights_off_no_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off

- alias: 'Bedroom tap face button after sunset'
  id: tap2_lights_off_after_sunset
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Hallway tap button two'
  id: tap1_guest_lights_off
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Two
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.guest_room_on

- alias: 'Bedroom tap button 2 bathroom run'
  id: tap2_bathroom_run
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Two
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_landing_light

- alias: 'Bedroom tap button 3 kitchen run'
  id: tap2_kitchen_run
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Three
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_to_kitchen

- alias: 'Hallway tap button 3 bathroom run'
  id: tap1_bathroom_run
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Three
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_landing_light

- alias: 'Hallway tap button 4 bathroom run'
  id: tap1_landing_off
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Four
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_landing_light_off

- alias: 'Kitchen under cupboard lights'
  id: kitchen_sensor_lights_on
  trigger:
    platform: mqtt
    topic: smartthings/Kitchen motion/motion
    payload: 'active'
  condition:
    condition: state
    entity_id: input_boolean.kitmocorr
    state: 'off'
  action:
    - service: light.toggle
      entity_id: light.kitchen_under_cupboard
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kitmocorr

- alias: 'Kitchen under cupboard lights no motion'
  id: kitchen_sensor_lights_off
  trigger:
    platform: mqtt
    topic: smartthings/Kitchen motion/motion
    payload: 'inactive'
  condition:
    condition: state
    entity_id: input_boolean.kitmocorr
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.kitmocorr

- alias: "Doorbell"
  id: doorbell
  trigger:
    platform: mqtt
    topic: smartthings/Doorbell/contact
    payload: "closed"
  condition:
    condition: state
    entity_id: input_boolean.halloween_bell
    state: 'off'
  action:
    - service: media_player.sonos_snapshot
      entity_id: media_player.kitchen
    - service: media_player.media_stop
      data:
        entity_id: media_player.kitchen
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: 0.60
    - service: media_player.play_media
      data:
        entity_id: media_player.kitchen
        media_content_id: http://apollo.lucien.me.uk/~dave/doorbell/sound.mp3
        media_content_type: audio/mp3
    - delay: '00:00:03'
    - service: media_player.sonos_restore
      entity_id: media_player.kitchen

- alias: "Doorbell Halloween"
  id: doorbell_halloween
  trigger:
    platform: mqtt
    topic: smartthings/Doorbell/contact
    payload: "closed"
  condition:
    condition: state
    entity_id: input_boolean.halloween_bell
    state: 'on'
  action:
    - service: media_player.sonos_snapshot
      entity_id: media_player.kitchen
    - service: media_player.media_stop
      data:
        entity_id: media_player.kitchen
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: 0.80
    - service: media_player.play_media
      data:
        entity_id: media_player.kitchen
        media_content_id: http://apollo.lucien.me.uk/~dave/doorbell/toccataandfugue.mp3
        media_content_type: audio/mp3
    - delay: '00:00:08'
    - service: media_player.sonos_restore
      entity_id: media_player.kitchen

- alias: "Doorbell Christmas"
  id: doorbell_christmas
  trigger:
    platform: mqtt
    topic: smartthings/Doorbell/contact
    payload: "closed"
  condition:
    condition: state
    entity_id: input_boolean.christmas_bell
    state: 'on'
  action:
    - service: media_player.sonos_snapshot
      entity_id: media_player.kitchen
    - service: media_player.media_stop
      data:
        entity_id: media_player.kitchen
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: 0.80
    - service: media_player.play_media
      data:
        entity_id: media_player.kitchen
        media_content_id: http://apollo.lucien.me.uk/~dave/doorbell/toccataandfugue.mp3
        media_content_type: audio/mp3
    - delay: '00:00:08'
    - service: media_player.sonos_restore
      entity_id: media_player.kitchen

- alias: "Fridge Door Alarm"
  id: fridge_door_alarm
  trigger:
    platform: state
    entity_id: sensor.fridge_door
    from: 'closed'
    to: 'open'
    for:
      hours: 0
      minutes: 60
      seconds: 0
  action:
    - service: scene.turn_on
      entity_id: scene.fridge_door_left_open
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.fridge_alarm

- alias: "Fridge Door Alarm Close"
  id: fridge_door_alarm_close
  trigger:
    platform: state
    entity_id: sensor.fridge_door
    from: 'open'
    to: 'closed'
  condition: 
    condition: state
    entity_id: input_boolean.fridge_alarm
    state: 'on'    
  action:
    - service: scene.turn_on
      entity_id: scene.fridge_door_recovery
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.fridge_alarm
