- alias: 'Sun fading'
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    below: 10.5
  action:
    - service: scene.turn_on
      entity_id: scene.sun_fading
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_going_down

- alias: 'Turn more lights on as the sun gets dimmer'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: state
    entity_id: input_boolean.sun_inhibit_action
    state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.more_lights

- alias: 'Dusk all lights on'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  condition:
    condition: state
    entity_id: input_boolean.sun_inhibit_action
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_on

- alias: 'Goodnight'
  trigger:
    platform: time
    after: "22:20:00"
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_going_down
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Tortoises night night'
  trigger:
    platform: time
    after: "18:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_off

- alias: 'Tortoise heating on'
  trigger:
    platform: time
    after: "21:30"
  condition:
    condition: state
    entity_id: input_boolean.tortheaters
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.Tortoise_ceramic_heat_on
      
- alias: 'Tortoises good morning'
  trigger:
    platform: time
    after: "06:15:00"
  action:
    - service: scene.turn_on
      entity_id: scene.all_tortoise_lights_on
    - service: scene.turn_on
      entity_id: scene.Tortoise_ceramic_heat_off

# This next one resets all automations at just after midnight, to on so that automations which
# are turned off as part of a manual override (a button push) reset to on again
- alias: 'Reset Automations'
  trigger:
    platform: time
    after: "00:00:01"
  action:
    - service: automation.turn_on
      entity_id: automation.Dusk_all_lights_on
    - service: automation.turn_on
      entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer

- alias: 'Good morning'
  trigger:
    platform: time
    after: "05:29:00"
  condition:
    condition: sun
    before: sunrise
    before_offset: "0:30:00"
  action:
    - service: scene.turn_on
      entity_id: scene.good_morning
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.alarm_sequence_running

- alias: 'WakeyWakeyRiseAndShine'
  trigger:
    platform: time
    after: "05:50:00"
  condition:
    condition: sun
    before: sunrise
    before_offset: "0:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.wakey_wakey

- alias: 'Reset bedroom light to sensible levels'
  trigger:
    platform: time
    after: "06:20:00"
  condition:
    condition: sun
    before: sunrise
    before_offset: "0:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on

# As a backstop, this also turns on the automations which the tap "off" buttons turn off to prevent the lights
# coming back on in summer when we're in bed early.
- alias: 'Turn off lights after sunrise'
  trigger:
    platform: numeric_state
    entity_id: sun.Sun
    value_template: '{{ state.attributes.elevation }}'
    above: 10.5
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: automation.turn_on
      entity_id: automation.Dusk_all_lights_on
    - service: automation.turn_on
      entity_id: automation.Turn_more_lights_on_as_the_sun_gets_dimmer
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.alarm_sequence_running

#
# Boggo standard pressed button on the tap - the sunset sequence hasn't started.
# result: just turn off lights.
#
- alias: 'Hallway tap face button'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off

#
# Special case tap off button - sunset sequence has started, ignore remainder of sequence.
# result: turn off lights, and set inhibit input_boolean to stop other automations firing.
#
- alias: 'Hallway tap face button'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Bedroom tap face button'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off

- alias: 'Bedroom tap face button'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Face
    payload: 'pressed'
  condition:
    condition: state
    entity_id: input_boolean.sun_going_down
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sun_inhibit_action

- alias: 'Hallway tap button two'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Two
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_on

- alias: 'Bedroom tap button 2 bathroom run'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Two
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_landing_light

- alias: 'Bedroom tap button 3 kitchen run'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Bedroom tap/Three
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_to_kitchen

- alias: 'Hallway tap button 3 kitchen run'
  trigger:
    platform: mqtt
    topic: huepoller/tap/Hallway tap/Three
    payload: 'pressed'
  action:
    service: scene.turn_on
    entity_id: scene.nighttime_to_kitchen

- alias: 'Kitchen under cupboard lights'
  trigger:
    platform: mqtt
    topic: smartthings/Kitchen motion/motion
    payload: 'active'
  condition:
    condition: state
    entity_id: input_boolean.kitmocorr
    state: 'off'
  action:
    - service: light.toggle
      entity_id: light.kitchen_under_cupboard
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kitmocorr

- alias: 'Kitchen under cupboard lights no motion'
  trigger:
    platform: mqtt
    topic: smartthings/Kitchen motion/motion
    payload: 'inactive'
  condition:
    condition: state
    entity_id: input_boolean.kitmocorr
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.kitmocorr

- alias: "Doorbell"
  trigger:
    platform: mqtt
    topic: smartthings/Doorbell/contact
    payload: "closed"
  action:
    - service: media_player.sonos_snapshot
      entity_id: media_player.dining_room
    - service: media_player.media_stop
      data:
        entity_id: media_player.dining_room
    - service: media_player.volume_set
      data:
        entity_id: media_player.dining_room
        volume_level: 0.60
    - service: media_player.play_media
      data:
        entity_id: media_player.dining_room
        media_content_id: http://apollo.lucien.me.uk/~dave/doorbell/sound.mp3
        media_content_type: audio/mp3
    - delay: '00:00:03'
    - service: media_player.sonos_restore
      entity_id: media_player.dining_room
