  sun_going_down:
    name: Sun is going down
  sun_inhibit_action:
    name: Inhibit sundown actions
  tortheaters:
    name: Tort Ceramics Control
  alarm_sequence_running:
    name: Morning Alarm running
  kitmocorr:
    name: Kitchen Motion Correction
  torts_sun_based:
    name: Tortoise lights with sun
  dining_override:
    name: Dining Room switches on
  normal_bell:
    name: Normal bell
  halloween_bell:
    name: Halloween Bell
  christmas_bell:
    name: Christmas Bell
  fridge_alarm:
    name: Fridge Alarm
  holiday:
    name: holiday
  latenight:
    name: latenight
  christmas_decs:
    name: Christmas Decorations
