- name: sun_fading
  entities:
    light.Front_Room:
      state: on
      brightness: 100
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_room_table_lamp:
      state: on
      brightness: 100
      xy_color: [ 0.5125, 0.4149 ]
    light.Landing:
      state: on
      brightness: 100
      xy_color: [ 0.5125, 0.4149 ]
    light.maries_room:
      state: on
      brightness: 85
      color_temp: 387

- name: more_lights
  entities:
    light.Front_Room:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_room_table_lamp:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Bottom_of_stairs:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Landing:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Dining_room:
      state: on
      brightness: 114
      color_temp: 387
    light.maries_room:
      state: on
      brightness: 95
      color_temp: 387

- name: All lights on
  entities:
    light.Landing:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Bottom_of_stairs:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_Room:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_room_table_lamp:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Hallway:
      state: on
      brightness: 114
      color_temp: 387
    light.Dining_room:
      state: on
      brightness: 114
      color_temp: 387
    light.Porch:
      state: on
      brightness: 54
    light.our_bedroom:
      state: on
      brightness: 114
      color_temp: 387
    light.maries_room:
      state: on
      brightness: 114
      color_temp: 387

- name: good morning
  entities:
    light.Landing:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
      transition: 60
    light.Bottom_of_stairs:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_Room:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_room_table_lamp:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Hallway:
      state: on
      brightness: 114
      color_temp: 387
    light.Dining_room:
      state: on
      brightness: 114
      color_temp: 387
    light.Porch:
      state: on
      brightness: 114
      color_temp: 387
    light.our_bedroom:
      state: on
      brightness: 80
      color_temp: 387
      transition: 60
    light.maries_room:
      state: on
      brightness: 114
      color_temp: 387

- name: wakey wakey
  entities:
    light.Landing:
      state: on
      brightness: 160
      xy_color: [ 0.5125, 0.4149 ]
      transition: 60
    light.Bottom_of_stairs:
      state: on
      brightness: 160
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_Room:
      state: on
      brightness: 160
      xy_color: [ 0.5125, 0.4149 ]
    light.Front_room_table_lamp:
      state: on
      brightness: 160
      xy_color: [ 0.5125, 0.4149 ]
    light.Hallway:
      state: on
      brightness: 127
      color_temp: 387
    light.Dining_room:
      state: on
      brightness: 114
      color_temp: 387
    light.Porch:
      state: on
      brightness: 54
    light.our_bedroom:
      state: on
      brightness: 191
      color_temp: 387
      transition: 20
    light.maries_room:
      state: on
      brightness: 114
      color_temp: 387

- name: All lights off
  entities:
    light.Landing:
      state: off
    light.Bottom_of_stairs:
      state: off
    light.Front_Room:
      state: off
    light.Front_room_table_lamp:
      state: off
    light.Hallway:
      state: off
    light.Dining_room:
      state: off
    light.Porch:
      state: off
    light.our_bedroom:
      state: off
    light.maries_room:
      state: off

- name: gaming time
  entities:
    light.Landing:
      state: off
    light.Bottom_of_stairs:
      state: off
    light.Front_Room:
      state: off
    light.Front_room_table_lamp:
      state: on
      brightness: 140
      xy_color: [ 0.5125, 0.4149 ]
    light.Hallway:
      state: off
    light.Dining_room:
      state: off
    light.Porch:
      state: off
    light.our_bedroom:
      state: off
    light.maries_room:
      state: off

- name: guest_room_off
  entities:
    light.maries_room:
      state: off

- name: guest_room_on
  entities:
    light.maries_room:
      state: on

- name: Bedtime
  entities:
    light.our_bedroom:
      state: on
      brightness: 60
      color_temp: 387

- name: All Tortoise on
  entities:
    switch.black_cage_heat_lamp:
      state: on
    switch.white_cage_heat_lamp:
      state: on
    switch.tortoise_uv_lamps:
      state: on
    switch.tortoise_ceramic_heaters:
      state: on

- name: All Tortoise off
  entities:
    switch.black_cage_heat_lamp:
      state: off
    switch.white_cage_heat_lamp:
      state: off
    switch.tortoise_uv_lamps:
      state: off
    switch.tortoise_ceramic_heaters:
      state: off

- name: All Tortoise lights on
  entities:
    switch.black_cage_heat_lamp:
      state: on
    switch.white_cage_heat_lamp:
      state: on
    switch.tortoise_uv_lamps:
      state: on

- name: All Tortoise lights off
  entities:
    switch.black_cage_heat_lamp:
      state: off
    switch.white_cage_heat_lamp:
      state: off
    switch.tortoise_uv_lamps:
      state: off

- name: Tortoise ceramic heat on
  entities:
    switch.tortoise_ceramic_heaters:
      state: on

- name: Tortoise ceramic heat off
  entities:
    switch.tortoise_ceramic_heaters:
      state: off

- name: Nighttime landing light
  entities:
    light.landing:
      state: on
      brightness: 70
      xy_color: [ 0.5125, 0.4149 ]

- name: Nighttime landing light off
  entities:
    light.landing:
      state: off

- name: Nighttime to kitchen
  entities:
    light.Landing:
      state: on
      brightness: 70
      xy_color: [ 0.5125, 0.4149 ]
    light.bottom_of_stairs:
      state: on
      brightness: 70
      xy_color: [ 0.5125, 0.4149 ]
    light.dining_room:
      state: on
      brightness: 60
      color_temp: 387
