  audio_alert:
    alias: "Audio alert"
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.sonos_unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: media_player.play_media
        data_template:
          entity_id: "{{ sonos_entity }}"
          media_content_id: "{{ media_location }}"
          media_content_type: "{{ content_type }}"
      - delay: "{{ play_length }}"
      - service: media_player.sonos_unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.sonos_restore
        data_template:
          entity_id: "{{ sonos_entity }}"
