# Weather Prediction
- platform: yr
  monitored_conditions:
    - symbol
    - pressure
    - humidity
    - temperature
    
- platform: mqtt
  name: "Fish temp top"
  state_topic: "pond/tele/SENSOR"
  value_template: '{{ value_json["DS18B20-1"]["Temperature"] }}'
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Fish temp bottom"
  state_topic: "pond/tele/SENSOR"
  value_template: '{{ value_json["DS18B20-2"]["Temperature"] }}'
  unit_of_measurement: "°C"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: template
  sensors:
    solar_elevation:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
      friendly_name: 'Sun elevation'
      unit_of_measurement: 'deg'
    sunrise:
      value_template: "{% set tempvar = ((as_timestamp(states.sun.sun.attributes.next_rising)) | timestamp_local) %}{{ tempvar[11:16] }}"
    sunset:
      value_template: "{% set tempvar = ((as_timestamp(states.sun.sun.attributes.next_setting)) | timestamp_local) %}{{ tempvar[11:16] }}"
