- platform: mqtt
  name: "Tortoise UV Lamps"
  state_topic: "smartthings/Tortoise UV Lamps/switch"
  command_topic: "smartthings/Tortoise UV Lamps/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Tortoise Ceramic Heaters"
  state_topic: "smartthings/Tortoise Ceramic Heaters/switch"
  command_topic: "smartthings/Tortoise Ceramic Heaters/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Black cage Heat Lamp"
  state_topic: "smartthings/black cage heat lamp/switch"
  command_topic: "smartthings/black cage heat lamp/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "White cage Heat Lamp"
  state_topic: "smartthings/white cage heat lamp/switch"
  command_topic: "smartthings/white cage heat lamp/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Fish air pump"
  state_topic: "smartthings/Fish Air Pump/switch"
  command_topic: "smartthings/Fish Air Pump/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Front room decorations"
  state_topic: "smartthings/living room decorations/switch"
  command_topic: "smartthings/living room decorations/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Porch decorations"
  state_topic: "smartthings/porch decorations/switch"
  command_topic: "smartthings/porch decorations/switch"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Pond Aeration"
  state_topic: "pond/stat/POWER"
  command_topic: "pond/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
