#
# THESE SWITCHES BEING CHANGED REQUIRES A RESTART OF THE SERVER FROM THE COMMAND LINE
# A RESTART FROM THE CONTROL PANEL DOESNT DO ENOUGH TO ADD NEW SWITCHES
#

- platform: mqtt
  name: "Pond Aeration"
  state_topic: "pond/stat/POWER"
  command_topic: "pond/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Front door decs"
  state_topic: "porchdecs/stat/POWER"
  command_topic: "porchdecs/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Salt lamp"
  state_topic: "tasmota01/stat/POWER"
  command_topic: "tasmota01/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false


